%===================================================================
function zdiff=fixedpt(z0,parms)
%===================================================================

parms.stance_foot = parms.stance_foot_init;

% %%%%%%% initial state %%%%%%%
z0_temp = [0 0 0 0 0 0 z0];
[~, ~, ~, ~, ~, ~, phi, phid, theta, thetad, psi, psid, ....
phi_lh, phi_lhd, theta_lh, theta_lhd, psi_lh, psi_lhd, theta_lk, theta_lkd, ...
phi_rh, phi_rhd, theta_rh, theta_rhd, psi_rh, psi_rhd, theta_rk, theta_rkd]= getstate(z0_temp);

%%%%%% onestep %%%%
z1 = onestep(z0,parms);

%%%%%%% final state %%
z1_temp = [0 0 0 0 0 0  z1];
[~, ~, ~, ~, ~, ~, phi_f, phid_f, theta_f, thetad_f, psi_f, psid_f, ....
phi_lh_f, phi_lhd_f, theta_lh_f, theta_lhd_f, psi_lh_f, psi_lhd_f, theta_lk_f, theta_lkd_f, ...
phi_rh_f, phi_rhd_f, theta_rh_f, theta_rhd_f, psi_rh_f, psi_rhd_f, theta_rk_f, theta_rkd_f]= getstate(z1_temp);

zdiff = [...
    phi-phi_f, ... 
    phid-phid_f, ...
    theta-theta_f, ...
    thetad - thetad_f , ...
    psi - psi_f , ...
    psid - psid_f, ....
    phi_lh - phi_rh_f, ...
    phi_lhd - phi_rhd_f, ...
    theta_lh - theta_rh_f, ...
    theta_lhd - theta_rhd_f, ...
    psi_lh - psi_rh_f, ...
    psi_lhd - psi_rhd_f, ...
    theta_lk - theta_rk_f, ...
    theta_lkd - theta_rkd_f, ...
    phi_rh - phi_lh_f, ...
    phi_rhd - phi_lhd_f, ...
    theta_rh - theta_lh_f, ...
    theta_rhd - theta_lhd_f, ...
    psi_rh - psi_lh_f, ...
    psi_rhd - psi_lhd_f, ...
    theta_rk - theta_lk_f, ...
    theta_rkd - theta_lkd_f, ...
    ];
